name: Continuous Deployment
on:
  push:
    branches: [dev]
jobs:
  listApps:
    name: Get a list of all apps
    runs-on: ubuntu-latest
    outputs:
      apps: ${{steps.get-all-apps.outputs.apps}}
      frontendApps: ${{steps.get-all-apps.outputs.frontendApps}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: lts/fermium
          cache: npm

      - name: Install Nrwl CLI
       
        run: npm install -g @nrwl/cli

      - name: Install dependencies
        run: sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Install npm dependencies
       
        run: npm ci

      - name: Cache Angular and NX dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{github.sha}}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-nx-

      - id: get-all-apps
        name: Get the list of apps
       
        run: |
          mapfile -d " " -t appsArr < <(nx affected:apps --plain --all | sed  's/simulators[^-]//; s/account[^-]\|account$//; s/dispatch[^-]//;  s/platform[^-]//' | sed 's/ $//')
           appsArr[-1]=$(echo "${appsArr[-1]}" | xargs)

           if [ -z "${appsArr[0]}" ]; then
             unset appsArr[-1]
             appsJson=[]
           else
             appsJson=$(printf '"%s"\n' "${appsArr[@]}" | jq  . | jq -s . | tr -d '\n')
           fi
           frontendAppsArr=('account' 'platform' 'simulators' 'dispatch')
           frontendAppsJson=$(printf '"%s"\n' "${frontendAppsArr[@]}" | jq  . | jq -s . | tr -d '\n')
           echo "::set-output name=apps::$appsJson"
           echo "::set-output name=frontendApps::$frontendAppsJson"

  buildDevFrontEnds:
    name: Build development front end apps
    runs-on: ubuntu-latest

    needs: [listApps]
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.listApps.outputs.frontendApps) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: lts/fermium
          cache: npm

      - name: Install Nrwl CLI
       
        run: npm install -g @nrwl/cli


      - name: Install dependencies
        run: sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Install npm dependencies
       
        run: npm ci

      - name: Cache Angular and NX dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ matrix.app }}-${{github.sha}}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ matrix.libOrApp }}
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-nx-

      - name: Build dev app
       
        run: mv libs/shared/environments/src/lib/environment.stage.ts libs/shared/environments/src/lib/environment.prod.ts && nx build ${{matrix.app}} --prod --with-deps

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.app}}-dev
          path: dist/apps/${{matrix.app}}
          retention-days: 5
          if-no-files-found: error

  buildProdFrontEnds:
    name: Build production front end apps
    runs-on: ubuntu-latest

    needs: [listApps]
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.listApps.outputs.frontendApps) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: lts/fermium
          cache: npm

      - name: Install Nrwl CLI       
        run: npm install -g @nrwl/cli


      - name: Install dependencies
        run: sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Install npm dependencies
       
        run: npm ci

      - name: Cache Angular and NX dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ matrix.app }}-${{github.sha}}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ matrix.app }}
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-nx-

      - name: Build prod app
       
        run:  nx build ${{matrix.app}} --prod --with-deps

      - name: Upload build

        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.app}}-prod
          path: dist/apps/${{matrix.app}}
          retention-days: 5
          if-no-files-found: error

  buildPushDockerImages:
    name: Build and push backend docker images
    runs-on: ubuntu-latest

    needs: [listApps]
    strategy:
      matrix:
        app: ${{ fromJson(needs.listApps.outputs.apps) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - if: matrix.app != 'combine-service'
        name: Build and Push Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.GHCR_USERNAME }}"
          password: "${{ secrets.GHCR_TOKEN }}"
          image_name: biosimulations/${{matrix.app}}
          image_tag: latest,${{github.sha}}
          push_git_tag: true
          registry: ghcr.io
          context: .
          dockerfile: Dockerfile
          build_extra_args: "--compress=true --build-arg app=${{matrix.app}}"

      - if: matrix.app == 'combine-service'
        name: Build and Push Python Image Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.GHCR_USERNAME }}"
          password: "${{ secrets.GHCR_TOKEN }}"
          image_name: biosimulations/${{matrix.app}}
          image_tag: latest,${{github.sha}}
          push_git_tag: true
          registry: ghcr.io
          context: .
          dockerfile: DockerfilePython
          build_extra_args: "--compress=true --build-arg app=${{matrix.app}}"
  deployDevFrontend:
    name: Publish the development frontend
    runs-on: ubuntu-latest
    needs: [listApps, buildDevFrontEnds, buildPushDockerImages]
    environment: dev_environment
    strategy:
      matrix:
        app: ${{ fromJson(needs.listApps.outputs.frontendApps) }}
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: lts/fermium
          
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Download Build for app
        uses: actions/download-artifact@v2
        with:
          name: ${{matrix.app}}-dev

      - name: Push App
        env:
          idKey: ${{matrix.app}}_site_id
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        run: |
          export NETLIFY_SITE_ID=${{secrets[env.idKey]}}
          export NETLIFY_AUTH_TOKEN=${{secrets.NETLIFY_AUTH_TOKEN}}
          netlify deploy --prod

  deployProdFrontend:
    name: Publish the production frontend
    runs-on: ubuntu-latest
    needs: [listApps, buildProdFrontEnds, buildPushDockerImages,deployDevFrontend]
    environment: prod_environment
    strategy:
      matrix:
        app: ${{ fromJson(needs.listApps.outputs.frontendApps) }}
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 15.x

      - name: Download Build for app
        uses: actions/download-artifact@v2
        with:
          name: ${{matrix.app}}-prod

      - name: Push App
        env:
          idKey: ${{matrix.app}}_site_id
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        run: |
          export NETLIFY_SITE_ID=${{secrets[env.idKey]}}
          export NETLIFY_AUTH_TOKEN=${{secrets.NETLIFY_AUTH_TOKEN}}
          netlify deploy --prod

  triggerDevDeployment:
    name: Trigger a new deployment of the dev backend
    runs-on: ubuntu-latest
    needs: [buildPushDockerImages, buildDevFrontEnds]
    environment: dev_environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Call Webhook
        env:
          GHCR_USERNAME: "${{ secrets.GHCR_USERNAME }}"
          GHCR_TOKEN: "${{ secrets.GHCR_TOKEN }}"
          BRANCH: ${{ secrets.OVERLAY }}
        run: |
          echo '{"ref": "master","inputs":{"overlay": "'$BRANCH'","tag":"'$GITHUB_SHA'"}}' >body
          curl -X POST 'https://api.github.com/repos/biosimulations/Biosimulations-Deployment/actions/workflows/deploy.yml/dispatches' -H 'Authorization: Bearer ${{ secrets.GHCR_TOKEN }}' -H 'Content-Type: application/json' --data "@body"

  triggerProdDeployment:
    name: Trigger a new deployment of the production backend
    runs-on: ubuntu-latest
    needs: [buildPushDockerImages, buildProdFrontEnds,triggerDevDeployment]
    environment: prod_environment
    steps:
      - name: Call Webhook
        env:
          GHCR_USERNAME: "${{ secrets.GHCR_USERNAME }}"
          GHCR_TOKEN: "${{ secrets.GHCR_TOKEN }}"
          BRANCH: ${{ secrets.NAME }}

        run: |
          echo '{"ref": "master","inputs":{"overlay": "'$BRANCH'","tag":"'$GITHUB_SHA'"}}' >body
          curl -X POST 'https://api.github.com/repos/biosimulations/Biosimulations-Deployment/actions/workflows/deploy.yml/dispatches' -H 'Authorization: Bearer ${{ secrets.GHCR_TOKEN }}' -H 'Content-Type: application/json' --data "@body"
  Release:
    runs-on: ubuntu-latest
    needs: [buildPushDockerImages, buildProdFrontEnds,triggerDevDeployment, triggerProdDeployment, deployProdFrontend,deployDevFrontend]
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{secrets.GH_RELEASE_TOKEN}}
          ref: dev
      - name: Configure CI Git User
        run: |
          git config --global user.name 'Biosimulations-Daemon'
          git config --global user.email 'biosimulationsdaemon@gmail.com'

      - uses: actions/setup-node@v2.3.0
        with:
          node-version: "12"
      - run: npm ci
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true 

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{secrets.GH_RELEASE_TOKEN}}
          GIT_CREDENTIALS: ${{secrets.GH_RELEASE_TOKEN}}
          GIT_AUTHOR_NAME: "Biosimulations-Daemon"
          GIT_AUTHOR_EMAIL: "biosimulationsdaemon@gmail.com"
          GIT_COMMITTER_NAME: "Biosimulations-Daemon"
          GIT_COMMITTER_EMAIL: "biosimulationsdaemon@gmail.com"
          
        run: npx semantic-release
