name: Continuous Integration
on:
  push:
  pull_request_target:
jobs:
  getAffectedLibrariesApps:
    env:
        NX_BRANCH: ${{ github.event.pull_request.head.ref }}  
    name: Determine affected libraries and apps
    runs-on: ubuntu-latest
    outputs:
      libs: ${{ steps.get-affected-libs-apps.outputs.libs }}
      apps: ${{ steps.get-affected-libs-apps.outputs.apps }}
      libsApps: ${{ steps.get-affected-libs-apps.outputs.libsApps }}
      run: ${{ steps.get-affected-libs-apps.outputs.run }}
      runApps: ${{ steps.get-affected-libs-apps.outputs.runApps }}
      runLibs: ${{ steps.get-affected-libs-apps.outputs.runLibs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Configure base commit
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            echo NX_BASE=origin/$GITHUB_BASE_REF >>$GITHUB_ENV
          else
          if [  ${{github.event.before}} == 0000000000000000000000000000000000000000 ]
          then
            echo NX_BASE=origin/dev >>$GITHUB_ENV
          else
            echo NX_BASE=${{ github.event.before }} >>$GITHUB_ENV
          fi
          fi

      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: lts/fermium
          cache: npm


      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install Pipenv and Flake8
        run: python -m pip install pipenv flake8

      - name: Install Python Dependencies
        run: pipenv install --dev

      - name: Install Nrwl CLI
       
        run: npm install -g @nrwl/cli

      - name: Install dependencies
        run: sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Install npm dependencies
        run: npm ci


      - id: get-affected-libs-apps
        name: Determine affected libraries and apps
       
        run: |
          mapfile -d " " -t libsArr < <( nx affected:libs --base=$NX_BASE --plain )
          mapfile -d " " -t appsArr < <( nx affected:apps --base=$NX_BASE --plain )
          libsArr[-1]=$(echo "${libsArr[-1]}" | xargs)
          appsArr[-1]=$(echo "${appsArr[-1]}" | xargs)
          run=true
          runApps=true
          runLubs=true

          if [ -z "${libsArr[0]}" ]; then
            unset libsArr[-1]
            libsJson=[]
            runLibs=false
          else
            libsJson=$(printf '"%s"\n' "${libsArr[@]}" | jq  . | jq -s . | tr -d '\n')
          fi

          if [ -z "${appsArr[0]}" ]; then
            unset appsArr[-1]
            appsJson=[]
            runApps=false
          else
            appsJson=$(printf '"%s"\n' "${appsArr[@]}" | jq  . | jq -s . | tr -d '\n')
          fi
          libsAppsArr=( "${libsArr[@]}" "${appsArr[@]}" )
          if [ "${#libsAppsArr[@]}" = "0" ]; then
            libsAppsJson=[]
            run=false
          else
            libsAppsJson=$(printf '"%s"\n' "${libsAppsArr[@]}" | jq  . | jq -s . | tr -d '\n')
          fi

          echo "::set-output name=libs::$libsJson"
          echo "::set-output name=apps::$appsJson"
          echo "::set-output name=libsApps::$libsAppsJson"
          echo "::set-output name=run::$run"
          echo "::set-output name=runApps::$runApps"
          echo "::set-output name=runLibs::$runLibs"

  lint:
    env:
        NX_BRANCH: ${{ github.event.pull_request.head.ref }}      
    name: Lint libraries and apps
    runs-on: ubuntu-latest

    needs: getAffectedLibrariesApps
    if: ${{ needs.getAffectedLibrariesApps.outputs.run == 'true' }}

    strategy:
      fail-fast: false
      matrix:
        libOrApp: ${{ fromJson(needs.getAffectedLibrariesApps.outputs.libsApps) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1

      - name: Configure base commit
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            echo NX_BASE=origin/$GITHUB_BASE_REF >>$GITHUB_ENV
          else
            echo NX_BASE=origin/deploy >>$GITHUB_ENV
          fi

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install Pipenv and Flake8
        run: python -m pip install pipenv flake8

      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: lts/fermium
          cache: npm


      - name: Install Nrwl CLI
       
        run: npm install -g @nrwl/cli



      - name: Install dependencies
       
        run: npm ci

      - name: Cache Angular and NX dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ matrix.libOrApp }}-${{github.sha}}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ matrix.libOrApp }}
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-nx-

      - name: Lint library or app (TypeScript)
        if: matrix.libOrApp != 'combine-service'
       
        run: nx run ${{ matrix.libOrApp }}:lint

      - name: Lint library or app (Python)
        if: matrix.libOrApp == 'combine-service'
       
        run: python -m flake8 apps/${{ matrix.libOrApp }}/src/

  build:
    env:
        NX_BRANCH: ${{ github.event.pull_request.head.ref }}      
    name: Build app
    runs-on: ubuntu-latest

    needs: getAffectedLibrariesApps
    if: ${{ needs.getAffectedLibrariesApps.outputs.run == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.getAffectedLibrariesApps.outputs.apps) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1

      - name: Configure base commit
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            echo NX_BASE=origin/$GITHUB_BASE_REF >>$GITHUB_ENV
          else
            echo NX_BASE=origin/deploy >>$GITHUB_ENV
          fi

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install Pipenv and Flake8
        run: python -m pip install pipenv flake8

      - name: Install Python dependencies
        if: matrix.libOrApp == 'combine-service'
       
        run: pipenv install --dev

      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: lts/fermium
          cache: npm


      - name: Install Nrwl CLI
       
        run: npm install -g @nrwl/cli

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-node-

      - name: Install dependencies
       
        run: npm ci

      - name: Cache Angular and NX dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ matrix.app }}-${{github.sha}}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ matrix.app }}
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-nx-

      - name: Build app and dependencies
       
        run: nx run ${{ matrix.app }}:build --prod --with-deps


  testApp:
    env:
        NX_BRANCH: ${{ github.event.pull_request.head.ref }}      
    name: Test app
    runs-on: ubuntu-latest

    needs: getAffectedLibrariesApps
    if: ${{ needs.getAffectedLibrariesApps.outputs.runApps == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        libOrApp: ${{ fromJson(needs.getAffectedLibrariesApps.outputs.apps) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1

      - name: Configure base commit
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            echo NX_BASE=origin/$GITHUB_BASE_REF >>$GITHUB_ENV
          else
            echo NX_BASE=origin/deploy >>$GITHUB_ENV
          fi

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install Pipenv and Flake8
        run: python -m pip install pipenv flake8

      - name: Install Python dependencies
        if: matrix.libOrApp == 'combine-service'
       
        run: pipenv install --dev

      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: lts/fermium
          cache: npm


      - name: Install Nrwl CLI
       
        run: npm install -g @nrwl/cli


      - name: Install dependencies
       
        run: npm ci

      - name: Cache Angular and NX dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ matrix.app }}-${{github.sha}}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ matrix.app }}
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-nx-

      - name: Test app (TypeScript)
       
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER }}
          API_AUDIENCE: ${{ secrets.API_AUDIENCE }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          MANAGEMENT_DOMAIN: ${{ secrets.MANAGEMENT_DOMAIN }}
          MANAGEMENT_ID: ${{ secrets.MANAGEMENT_ID }}
          MANAGEMENT_SECRET: ${{ secrets.MANAGEMENT_SECRET }}
        if: matrix.libOrApp != 'combine-service'
        run: nx run ${{ matrix.libOrApp }}:build --prod --with-deps && nx run ${{ matrix.libOrApp }}:test --coverage

      - name: Validate OpenAPI specification for library or app (Python)
        if: matrix.libOrApp == 'combine-service'
        run: |
          # ./node_modules/.bin/openapi-examples-validator apps/${{ matrix.libOrApp }}/src/spec/spec.yml

      - name: Test library or app (Python)
        if: matrix.libOrApp == 'combine-service'
        uses: GabrielBB/xvfb-action@v1
        env:
          PYTHONPATH: apps/${{ matrix.libOrApp }}/
        with:
          run: pipenv run python -m pytest --cov apps/${{ matrix.libOrApp }}/src/ apps/${{ matrix.libOrApp }}/tests/

      - name: Upload coverage data to Codecov
        uses: codecov/codecov-action@v2.0.1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      
  testLib:
    env:
        NX_BRANCH: ${{ github.event.pull_request.head.ref }}      
    name: Test library or app
    runs-on: ubuntu-latest

    needs: getAffectedLibrariesApps
    if: ${{ needs.getAffectedLibrariesApps.outputs.runLib == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        libOrApp: ${{ fromJson(needs.getAffectedLibrariesApps.outputs.libs) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1

      - name: Configure base commit
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            echo NX_BASE=origin/$GITHUB_BASE_REF >>$GITHUB_ENV
          else
            echo NX_BASE=origin/deploy >>$GITHUB_ENV
          fi

      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: lts/fermium
          cache: npm

      - name: Install Nrwl CLI
       
        run: npm install -g @nrwl/cli


      - name: Install dependencies
       
        run: npm ci

      - name: Cache Angular and NX dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ matrix.libOrApp }}-${{github.sha}}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}-${{ matrix.libOrApp }}
            ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-nx-
     
      - name: Test library 
       
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER }}
          API_AUDIENCE: ${{ secrets.API_AUDIENCE }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          MANAGEMENT_DOMAIN: ${{ secrets.MANAGEMENT_DOMAIN }}
          MANAGEMENT_ID: ${{ secrets.MANAGEMENT_ID }}
          MANAGEMENT_SECRET: ${{ secrets.MANAGEMENT_SECRET }}
        if: matrix.libOrApp != 'combine-service'
        run: nx run ${{ matrix.libOrApp }}:test --coverage

      - name: Validate OpenAPI specification for library or app (Python)
        if: matrix.libOrApp == 'combine-service'
        run: |
          # ./node_modules/.bin/openapi-examples-validator apps/${{ matrix.libOrApp }}/src/spec/spec.yml

      - name: Test library or app (Python)
        if: matrix.libOrApp == 'combine-service'
        uses: GabrielBB/xvfb-action@v1
        env:
          PYTHONPATH: apps/${{ matrix.libOrApp }}/
        with:
          run: pipenv run python -m pytest --cov apps/${{ matrix.libOrApp }}/src/ apps/${{ matrix.libOrApp }}/tests/

      - name: Upload coverage data to Codecov
        uses: codecov/codecov-action@v2.0.1
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  buildPushDockerImages:
    name: Build Docker image for app
    runs-on: ubuntu-latest

    needs: [getAffectedLibrariesApps]
    if: ${{ needs.getAffectedLibrariesApps.outputs.run == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.getAffectedLibrariesApps.outputs.apps) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - if: matrix.app != 'combine-service'
        name: Build Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.GHCR_USERNAME }}"
          password: "${{ secrets.GHCR_TOKEN }}"
          image_name: biosimulations/${{matrix.app}}
          image_tag: ${{ env.BRANCH_NAME }}
          push_image_and_stages: ${{github.event_name == 'pull_request'}}
          registry: ghcr.io
          context: .
          dockerfile: Dockerfile
          build_extra_args: "--build-arg app=${{matrix.app}}"

      - if: matrix.app == 'combine-service'
        name: Build Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.GHCR_USERNAME }}"
          password: "${{ secrets.GHCR_TOKEN }}"
          image_name: biosimulations/${{matrix.app}}
          image_tag: ${{ env.BRANCH_NAME }}
          push_image_and_stages: ${{github.event_name == 'pull_request'}}
          registry: ghcr.io
          context: .
          dockerfile: DockerfilePython
          build_extra_args: "--build-arg app=${{matrix.app}}"

  markDone:
    name: Mark CI as complete
    needs: [getAffectedLibrariesApps, lint, testApp, testLib, build, buildPushDockerImages]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo "CI PASSED"
