name: Generate a report of the licenses of the dependencies
on:
  push:
    branches: [dev]
jobs:
  dependency-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN}}

      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: lts/fermium
          cache: npm


      - name: Generate license report
       
        run: |
          npm install -g license-checker
          npm ci
          npm run gen-dependency-license-report
          
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          
      - name: Commit Changes 
        uses: EndBug/add-and-commit@v7.2.1 # You can change this to use a specific version
        with:
          author_name: Biosimulations-Daemon
          author_email: biosimulationsdaemon@gmail.com
          branch: dev
          message: 'chore: updated dependency licences [skip ci]'
          signoff: true
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN}} # Leave this line unchanged       
